### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by mkulagowski** [mkulagowski/MineZPRaft#1]
We have to write basic documentation, print it out and deliver it to our supervisor.
 - Maximum length: 3 pages of A4 format.
 - Printed out.
 - Project description
 - List of components
  - List of functionalities
 - Issues timesheet (table)
  - Each issue may be split into subissues
  - Each subissue has a number of manhours
  - Manhours are summed for each issue
  - Manhours are summed for whole project for each member
  - Each member should have >=15 manhours planned for him
  - Whole project should have >=30 manhours

Here is source text from Mr. Biedrzycki:
```
Specyfikację wstępną proszę przynieść w formie papierowej, można ją wsunąć pod drzwi pokoju 215, należy tylko zaznaczyć kto jest jej odbiorcą, kto autorem i w związku z jakim przedmiotem powstała.
Dokumentacja ta powinna zawierać rozwinięty opis tematu zadania, pokazujący że Państwo wiedzą co mają zrobić.
Oprócz tego należy w niej umieścić listę funkcjonalności do zrealizowania, np. dla tematu "Tester GUI":
Funkcjonalności: 1) testowanie przycisku, 2) testowanie komponentu "text input" 3) testowanie komponentu "label" 4) porównywanie bitmap 5) porównywanie stanu kontrolek posiadających stan.

W dokumentacji wstępnej należy również umieścić tabelę z listą zadań oraz oszacowaniem czasu jaki zostanie poświęcony na każde z nich, czyli dany problem należy zdekomponować na zadania.
Każde z nich dekomponujemy na podzadania. Postępujemy tak, aż dojdziemy do tak prostych zadań, że da się oszacować ich pracochłonność (w godzinach).
Proszę dodać do tabeli wiersz z sumą godzin na wszystkie zadania. Suma ta powinna wynosić >=15h na osobę, czyli zwykle >=30h.
Nie oczekuję, że to co Państwo zaplanują zgodzi się z rzeczywistością, zgodność ta przychodzi wraz z doświadczeniem w dekomponowaniu/oszacowywaniu i danej tematyce.
```

**Comment by mkulagowski** [comment]
I guess it may be hard to just sit and write all of it. That's why I've made spreadsheet on google docs - only the 2 of us can edit it (with amplitron mails).
It's already filled with first 2 tasks that we've been assigned and some sample number of manhours.
Please stick to the style - I think, we'll be able to just copy it over to the documentation, so no effort lost there ;)

[SPREADSHEET](https://docs.google.com/a/amp.pw.edu.pl/spreadsheets/d/1YYuNdBW20qqHLANcP1H615IP6N4bxu_V1S1ietTxGNs/edit?usp=sharing)

Please check it and give ur opinion. I've sent mail to our supervisor asking if whole project (along with documentation) can be written in english. Let's hope for big, fat 'YES'.

**Comment by LKostyra** [comment]
Added filled Renderer part (I think this will be all we need from it) and a start of Game Manager. More to come in the afternoon.

Moreover, I let myself edit some parts of the excel to automagically recalculate stuff for us.

**Comment by mkulagowski** [comment]
I've made docs on google to write [basic documentation](https://docs.google.com/a/amp.pw.edu.pl/document/d/1Ftak9TyZmiSdzYfpEokjTLoIqpgoT8VaBZTKqA13dUc/edit?usp=sharing). Not sure if today or tomorrow, but I'll try to fill it out.

We have to get in touch tomorrow and call each other, so we can end it tomorrow (timesheet as well)

**Comment by mkulagowski** [comment]
I've made some big changes in documentation docs.
On tuesday, when we'll be returning our documentation we should ask about our coding style. In project [THIS](http://staff.elka.pw.edu.pl/~rbiedrzy/ZPR/StylKodowania.html) ought to be used...or we can use our own IF Mr. Biedrzycki says yes.

Documentation I've written in polish afterall. If you see it important to write it in english, be my guest & translate or write from scratch. If it stays polish, then excel Timesheet will also have to be translated to polish. Project & comments in english nevertheless.

**Comment by LKostyra** [comment]
This is more or less the same code style that we use. The difference I see is that our code is more spacious (ex. according to Linux Kernel style:

    if (something) {
        doSomeStuff;
    }

vs. Mr. Biedrzyckis proposal:

    if(something){
        doStuff;
    }

)

I don't think this will be a problem. However, we do need to ask Mr. Biedrzycki if entry-level docs can be in Polish. I'll leave sending the mail to you, in the meantime I'll go through the documentation.

**Comment by mkulagowski** [comment]
Entry-level docs CAN be in polish from the beginning. Question for docs in english was a special permission request :P

**Comment by LKostyra** [comment]
OK, I think there is no need to fight for english version of the docs. We'll do it in Polish.

**Comment by mkulagowski** [comment]
With our joined effort, we managed to write few pages of entry-lvl docs.
Well done. First milestone is behind us now.
